#!/bin/sh
export FLASK_APP="/app/server/serving_static/serve.py"
echo "STARTING FLASK SERVER"
python3 /app/server/serving_static/serve.py &
echo "STARTING MUSIC GPIO INTERFACE"
python3 /app/server/serving_static/music.py &
